version: "3.9"
services:
  web:
    build: .
    ports:
      - "80"
    depends_on:
      - mongodb
    env_file:
      - prod.env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cyclops
      MONGO_INITDB_ROOT_PASSWORD: GbP9gw4Oi47hS7sd
    volumes:
      - mongodb_data:/data/db

  celery_worker:
    build: .
    command: celery -A library.tasks worker -P eventlet --loglevel=INFO
    depends_on:
      - mongodb
    env_file:
      - prod.env
    volumes:
      - ./celery_beat_schedule:/app/celery_beat_schedule

  celery_beat:
    build: .
    command: celery -A library.tasks beat --loglevel=INFO
    depends_on:
      - mongodb
    env_file:
      - prod.env
    volumes:
      - ./celery_beat_schedule:/app/celery_beat_schedule

volumes:
  mongodb_data:
